name: test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: action
              uses: actions/checkout@v3

            - name: node.js install
              uses: actions/setup-node@v3

              with: 
                node-version: 18

            - name: Install Dependencies
              run: npm ci

            - name: buid
              run: npm run build 

            - name: test pass
              run: echo "working"
